include:
  - project: 'BetterCorp/cicd'
    ref: master
    file: '/bsb-cicd.yml'

test:npm:
  image: node:lts-alpine
  tags:
    - build
    - docker
  stage: test:npm
  dependencies:
    - version:npm
    - build:npm
  before_script:
    - npm ci
  script:
    - ./node_modules/mocha/bin/mocha
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml