# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches:
      - "**"
      #- "!master"
      #- "!develop"
      - "!release"
    tags-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: lite/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        working-directory: lite/
      - run: npm run build
        working-directory: lite/

      - run: npm ci
        working-directory: heavy/
      - run: npm run build
        working-directory: heavy/

      - run: npm ci
        working-directory: node/
      - run: npm run build
        working-directory: node/

      - run: npm run test
        working-directory: lite/
  
  buildDocs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: documentation/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        working-directory: documentation/

      - run: npm run build
        working-directory: documentation/
