name: Publish Release

on:
  push:
    branches:
      - "release"

jobs:
  buildTag:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: semver
        id: semver
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          branch: release
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          change_path: "./"
          bump_each_commit: true
          namespace: ""

      - run: rm -f ~/.npmrc ; rm -f ./.npmrc ; echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM2_TOKEN_PUB }}" > ./.npmrc
      - run: |
          git config user.name "${{ secrets.NPM_NAME }}";
          git config user.email "${{ secrets.NPM_EMAIL }}";
          echo "Hello $(git config --get user.name)";
      - run: npm run build
      # - run: npm test
      - name: output version
        run: |
          echo "Setting version too: ${{ steps.semver.outputs.version }}";
      - run: npm version ${{ steps.semver.outputs.version }}
      - run: npm config set sign-git-tag true
      - run: npm publish

      - uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.semver.outputs.version }}"
          name: "v${{ steps.semver.outputs.version }}"
          body: "See release: https://www.npmjs.com/package/@bettercorp/tools/v/${{ steps.semver.outputs.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: cleanup
        if: always()
        run: rm -f ~/.npmrc ; rm -f ./.npmrc;
