name: Publish Release

on:
  create:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: lite/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - run: npm i -g typescript ts-node
      - run: tsc -v ; ts-node -v ; node -v

      - run: npm ci
        working-directory: lite/

      - run: npm ci
        working-directory: heavy/

      - run: npm ci
        working-directory: node/

      - name: semver
        id: semver
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${patch}"
          change_path: "./"
          bump_each_commit: true

      - run: npm version ${{ steps.semver.outputs.version }}.0 --no-git-tag-version
        working-directory: lite/

      - run: npm run build
        working-directory: lite/

      - run: npm version ${{ steps.semver.outputs.version }}.1 --no-git-tag-version
        working-directory: heavy/

      - run: npm run build
        working-directory: heavy/

      - run: npm version ${{ steps.semver.outputs.version }}.2 --no-git-tag-version
        working-directory: node/

      - run: npm run build
        working-directory: node/

      - run: npm run test
        working-directory: lite/

      - name: Test Report
        uses: dorny/test-reporter@v1.7.0
        with:
          name: Tests
          path: lite/junit.json
          reporter: mocha-json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: "lite/coverage"

      - run: npm publish
        working-directory: lite/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - run: npm publish --tag heavy
        working-directory: heavy/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - run: npm publish --tag node
        working-directory: node/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.semver.outputs.version }}"
          name: "v${{ steps.semver.outputs.version }}"
          body: "See release: https://www.npmjs.com/package/@bettercorp/tools/v/${{ steps.semver.outputs.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}

  releaseDocs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
        working-directory: documentation/

      - run: npm run build
        working-directory: documentation/

      - name: Update site
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish documentation/.vuepress/dist --project-name=better-tools  --branch=master
